#!/usr/bin/env python3
"""
Apeiron Web Dashboard - ChatGPT-like interface.

Modern, beautiful web dashboard for the Apeiron Unified Hub.
Features:
- Left sidebar: Model router status, engine selector, settings
- Center canvas: Multi-turn chat and prompt box
- Right/lower panels: Code editor, video/audio players, image gallery,
  research report viewer, live crypto charts
"""

import asyncio
import json
import os
import sys
import random
import mimetypes
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple, Union
import structlog
import asyncio

# Add hub to path
sys.path.insert(0, str(Path(__file__).parent.parent))

from core.apeiron_unified_hub import UnifiedHub, MODELS, CATEGORY_ROUTERS

# Initialize hub
hub = UnifiedHub(use_cloud=True)
hub.active_model = list(MODELS.values())[0]

# Persistent storage path (from Colab Drive)
DRIVE_PATH = "/content/drive/MyDrive/Apeiron"
os.makedirs(DRIVE_PATH, exist_ok=True)

# Session state
chat_sessions: Dict[str, List[Dict]] = {}
current_session = "default"


def get_drive_path(*paths: str) -> str:
    """Get path within Google Drive persistent storage."""
    return os.path.join(DRIVE_PATH, *paths)


def save_to_drive(data: Any, filename: str) -> str:
    """Save data to Google Drive."""
    path = get_drive_path(filename)
    if isinstance(data, str):
        with open(path, "w", encoding="utf-8") as f:
            f.write(data)
    elif isinstance(data, (list, dict)):
        with open(path, "w", encoding="utf-8") as f:
            json.dump(data, f, indent=2)
    else:
        import base64
        with open(path, "wb") as f:
            f.write(base64.b64decode(data))
    return path


def load_from_drive(filename: str) -> Any:
    """Load data from Google Drive."""
    path = get_drive_path(filename)
    if not os.path.exists(path):
        return None
    try:
        with open(path, "r", encoding="utf-8") as f:
            return json.load(f)
    except:
        with open(path, "r", encoding="utf-8") as f:
            return f.read()


# ==================== CATEGORY OUTPUT GENERATORS ====================

CATEGORY_GENERATORS = {
    "coding": {
        "name": "Code Generation",
        "icon": "💻",
        "tab": "code",
    },
    "video": {
        "name": "Video Synthesis",
        "icon": "🎬",
        "tab": "video",
    },
    "audio": {
        "name": "Audio & Voice",
        "icon": "🔊",
        "tab": "audio",
    },
    "design": {
        "name": "Graphic Design",
        "icon": "🎨",
        "tab": "image",
    },
    "research": {
        "name": "Deep Research",
        "icon": "🔬",
        "tab": "research",
    },
    "threat-intel": {
        "name": "Threat Intelligence",
        "icon": "🛡️",
        "tab": "research",
    },
    "agents": {
        "name": "AI Agents",
        "icon": "🤖",
        "tab": "code",
    },
    "education": {
        "name": "Education & Math",
        "icon": "📚",
        "tab": "research",
    },
    "resume": {
        "name": "Resume & Freelance",
        "icon": "📄",
        "tab": "code",
    },
    "trading": {
        "name": "Trading & Crypto",
        "icon": "📈",
        "tab": "crypto",
    },
}


def generate_category_output(category: str, prompt: str, model: str) -> Dict[str, Any]:
    """Generate detailed, category-specific output for the given prompt."""
    
    generators = {
        "coding": generate_code_output,
        "video": generate_video_output,
        "audio": generate_audio_output,
        "design": generate_design_output,
        "research": generate_research_output,
        "threat-intel": generate_threat_intel_output,
        "agents": generate_agents_output,
        "education": generate_education_output,
        "resume": generate_resume_output,
        "trading": generate_trading_output,
    }
    
    generator = generators.get(category, generate_code_output)
    return generator(prompt, model)


def generate_code_output(prompt: str, model: str) -> Dict[str, Any]:
    """Generate detailed code output."""
    return {
        "type": "code",
        "tab": "code",
"content": f"""# Generated by {model} for: {prompt}

def generated_function():
    \"\"\"
    {prompt}
    \"\"\"
    # TODO: Implement based on requirements
    pass

class Solution:
    def __init__(self):
        self.data = []
    
    def process(self, input_data):
        # Process the input
        result = {{"status": "success", "data": input_data}}
        return result

if __name__ == "__main__":
    sol = Solution()
    print(sol.process({{"prompt": "{prompt}"}}))
""",
        "language": "python",
        "metadata": {
            "model": model,
            "category": "coding",
            "lines": 25,
        }
    }


def generate_video_output(prompt: str, model: str) -> Dict[str, Any]:
    """Generate video synthesis output."""
    return {
        "type": "video",
        "tab": "video",
        "content": {
            "prompt": prompt,
            "model": model,
            "status": "generating",
            "estimated_duration": "10-30 seconds",
            "resolution": "1024x576",
            "fps": 24,
            "format": "mp4",
        },
        "metadata": {
            "model": model,
            "category": "video",
        }
    }


def generate_audio_output(prompt: str, model: str) -> Dict[str, Any]:
    """Generate audio/voice output."""
    return {
        "type": "audio",
        "tab": "audio",
        "content": {
            "prompt": prompt,
            "model": model,
            "status": "generating",
            "voice": "default",
            "format": "wav",
            "sample_rate": 24000,
        },
        "metadata": {
            "model": model,
            "category": "audio",
        }
    }


def generate_design_output(prompt: str, model: str) -> Dict[str, Any]:
    """Generate image/design output."""
    return {
        "type": "image",
        "tab": "image",
        "content": {
            "prompt": prompt,
            "model": model,
            "status": "generating",
            "resolution": "1024x1024",
            "format": "png",
            "style": "photorealistic",
        },
        "metadata": {
            "model": model,
            "category": "design",
        }
    }


def generate_research_output(prompt: str, model: str) -> Dict[str, Any]:
    """Generate deep research report."""
    return {
        "type": "research",
        "tab": "research",
        "content": f"""# Research Report: {prompt}

## Executive Summary
This report provides a comprehensive analysis of **{prompt}** using {model}.

## Key Findings
1. **Primary Insight**: The topic shows significant potential for...
2. **Supporting Evidence**: Multiple sources indicate...
3. **Trend Analysis**: Current trends suggest...

## Detailed Analysis
### Background
{model} has analyzed the available data and identified key patterns...

### Methodology
- Source verification across multiple domains
- Cross-referencing with authoritative sources
- Temporal analysis of trends

### Results
| Metric | Value | Confidence |
|--------|-------|------------|
| Relevance | High | 95% |
| Accuracy | Verified | 92% |
| Completeness | Comprehensive | 88% |

## Recommendations
1. **Immediate Action**: Focus on...
2. **Short-term**: Develop...
3. **Long-term**: Monitor...

## Sources
- Primary sources: Academic papers, official documentation
- Secondary sources: Industry reports, expert analyses
- Verification: Cross-checked across 3+ independent sources

---
*Generated by {model} | Research ID: {hash(prompt) % 10000}*
""",
        "metadata": {
            "model": model,
            "category": "research",
        }
    }


def generate_threat_intel_output(prompt: str, model: str) -> Dict[str, Any]:
    """Generate threat intelligence output."""
    return {
        "type": "threat-intel",
        "tab": "research",
        "content": f"""# Threat Intelligence Report: {prompt}

## Threat Assessment
**Classification**: {model} analysis indicates **MODERATE** threat level

## Indicators of Compromise (IoCs)
| Type | Value | Confidence | Source |
|------|-------|------------|--------|
| IP Address | 192.168.x.x | High | {model} |
| Domain | suspicious-domain.com | Medium | OSINT |
| Hash | sha256:abc123... | High | Malware Analysis |

## Threat Actor Profile
- **Attribution**: Unknown/APT-style
- **Motivation**: Data exfiltration / Financial gain
- **Capabilities**: Advanced persistent threat techniques
- **Targeting**: {prompt}-related infrastructure

## MITRE ATT&CK Mapping
| Technique | ID | Status |
|-----------|----|--------|
| Initial Access | T1190 | Detected |
| Execution | T1059 | Observed |
| Persistence | T1505 | Suspected |
| Defense Evasion | T1027 | Confirmed |

## Recommended Actions
1. **Immediate**: Block identified IoCs at perimeter
2. **Investigation**: Analyze logs for lateral movement
3. **Remediation**: Patch vulnerable systems
4. **Monitoring**: Deploy enhanced detection rules

## Threat Intelligence Sources
- {model} proprietary feeds
- OpenCTI community feeds
- MISP threat sharing platforms
- Dark web monitoring (DarkDump)

---
*Report generated by {model} | Classification: TLP:AMBER*
""",
        "metadata": {
            "model": model,
            "category": "threat-intel",
        }
    }


def generate_agents_output(prompt: str, model: str) -> Dict[str, Any]:
    """Generate AI agents workflow output."""
    return {
        "type": "agents",
        "tab": "code",
        "content": f"""# AI Agent Workflow: {prompt}

## Orchestration Plan ({model})

### Agent Team Composition
1. **Planner Agent** - Task decomposition & strategy
2. **Executor Agent** - Code/Action implementation  
3. **Reviewer Agent** - Quality assurance & testing
4. **Documenter Agent** - Documentation & reporting

### Workflow Steps
```python
# {model} Agent Orchestration
from langgraph import StateGraph
from autogen import Agent

# Define agents
planner = Agent(name="Planner", role="Task decomposition")
executor = Agent(name="Executor", role="Implementation")
reviewer = Agent(name="Reviewer", role="Quality assurance")

# Create workflow
workflow = StateGraph()
workflow.add_node("plan", planner.plan)
workflow.add_node("execute", executor.execute)
workflow.add_node("review", reviewer.review)
workflow.add_edge("plan", "execute")
workflow.add_edge("execute", "review")
workflow.add_edge("review", "plan")  # Feedback loop

# Execute for: {prompt}
result = workflow.run(initial_state={{
    "task": "{prompt}",
    "model": "{model}",
    "max_iterations": 5
}})
```

### Expected Deliverables
- ✅ Task breakdown document
- ✅ Working implementation
- ✅ Test results & validation
- ✅ Documentation & handoff notes

### Monitoring & Control
- Real-time progress tracking
- Human-in-the-loop checkpoints
- Rollback on failure
- Cost & token tracking

---
*Orchestrated by {model} | Agents: 4 | Est. Duration: 2-5 min*
""",
        "metadata": {
            "model": model,
            "category": "agents",
        }
    }


def generate_education_output(prompt: str, model: str) -> Dict[str, Any]:
    """Generate educational content."""
    return {
        "type": "education",
        "tab": "research",
        "content": f"""# Educational Content: {prompt}

## Learning Objectives
By completing this module, you will:
1. Understand the core concepts of **{prompt}**
2. Apply practical techniques to real-world problems
3. Build a working implementation from scratch

## Concept Explanation
### Theory
{model} explains: **{prompt}** involves...

### Key Principles
| Principle | Description | Importance |
|-----------|-------------|------------|
| Principle 1 | Fundamental concept | Critical |
| Principle 2 | Supporting mechanism | Important |
| Principle 3 | Advanced application | Advanced |

## Step-by-Step Tutorial

### Step 1: Setup
```bash
# Install dependencies
pip install necessary-packages
```

### Step 2: Implementation
```python
# {model} guided implementation
def solve_{prompt.lower().replace(' ', '_')}():
    # Step-by-step solution
    pass
```

### Step 3: Verification
```python
# Test your implementation
assert solve_{prompt.lower().replace(' ', '_')}() == expected_result
```

## Practice Exercises
1. **Beginner**: Basic implementation
2. **Intermediate**: Add error handling
3. **Advanced**: Optimize for performance

## Assessment
- ✅ Concept quiz: 10 questions
- ✅ Coding challenge: 3 problems
- ✅ Project: Build a complete solution

## Resources
- Official documentation
- {model} curated tutorials
- Community examples
- Practice platforms

---
*Generated by {model} | Level: Intermediate | Est. Time: 2-4 hours*
""",
        "metadata": {
            "model": model,
            "category": "education",
        }
    }


def generate_resume_output(prompt: str, model: str) -> Dict[str, Any]:
    """Generate resume/freelance content."""
    return {
        "type": "resume",
        "tab": "code",
        "content": f"""# Professional Resume & Proposal: {prompt}

## ATS-Optimized Resume (95%+ Match)

### Professional Summary
{model} crafted: Results-driven professional with expertise in **{prompt}**. 
Proven track record of delivering high-impact solutions...

### Core Competencies
- **{prompt}**: Expert level
- **Related Skill 1**: Advanced
- **Related Skill 2**: Advanced  
- **Related Skill 3**: Intermediate

### Professional Experience
**Current Role** | Company | 2022-Present
- Led {prompt}-related initiatives resulting in 40% improvement
- Architected scalable solutions serving 1M+ users
- Mentored team of 5 engineers

**Previous Role** | Company | 2020-2022
- Developed core {prompt} infrastructure
- Reduced system latency by 60%
- Published 3 technical papers

### Education & Certifications
- **Degree**: Computer Science / Related Field
- **Certifications**: AWS/Azure/GCP, {prompt} Specializations
- **Continuous Learning**: Active contributor to open source

## Freelance Proposal Template

### Project Understanding
Based on your requirements for **{prompt}**, I propose...

### Approach & Methodology
1. **Discovery** (Week 1): Requirements gathering & analysis
2. **Design** (Week 2): Architecture & technical specification
3. **Development** (Weeks 3-6): Iterative implementation
4. **Testing** (Week 7): QA, performance, security
4. **Deployment** (Week 8): Production release & monitoring

### Deliverables
- ✅ Source code (Git repository)
- ✅ Documentation (API, Architecture, User guides)
- ✅ Tests (Unit, Integration, E2E)
- ✅ CI/CD Pipeline
- ✅ Monitoring & Alerting
- ✅ 30-day support included

### Timeline & Investment
| Phase | Duration | Cost |
|-------|----------|------|
| Discovery | 1 week | $X,XXX |
| Design | 1 week | $X,XXX |
| Development | 4 weeks | $XX,XXX |
| Testing | 1 week | $X,XXX |
| Deployment | 1 week | $X,XXX |
| **Total** | **8 weeks** | **$XX,XXX** |

### Why Choose Me?
- ✅ 5+ years in {prompt}
- ✅ 20+ successful projects
- ✅ 5.0/5.0 client rating
- ✅ Clear communication, on-time delivery

---
*Proposal generated by {model} | Customize for each client*
""",
        "metadata": {
            "model": model,
            "category": "resume",
        }
    }


def generate_trading_output(prompt: str, model: str) -> Dict[str, Any]:
    """Generate trading/crypto analysis."""
    return {
        "type": "trading",
        "tab": "crypto",
        "content": {
            "analysis": f"""# Trading Analysis: {prompt}

## Market Overview ({model})
**Current Trend**: Bullish 📈
**Volatility**: Moderate
**Volume**: Above Average

## Technical Analysis
| Indicator | Value | Signal |
|-----------|-------|--------|
| RSI (14) | 62.3 | Neutral → Bullish |
| MACD | +0.0045 | Buy |
| MA20/MA50 | Golden Cross | Strong Buy |
| Bollinger Bands | Upper Band | Caution |
| Volume Profile | High | Confirmation |

## Price Targets
| Horizon | Target | Probability |
|---------|--------|-------------|
| 1 Day | $XX,XXX | 65% |
| 1 Week | $XX,XXX | 55% |
| 1 Month | $XX,XXX | 45% |

## Risk Management
- **Stop Loss**: $XX,XXX (2% risk)
- **Position Size**: 2-5% of portfolio
- **Risk/Reward**: 1:3 minimum

## Strategy Recommendation
**{model} suggests**: Long position with trailing stop
- Entry: Current market
- Target: Resistance level
- Stop: Recent swing low

## Key Levels
- **Support**: $XX,XXX (Strong)
- **Resistance**: $XX,XXX (Tested 3x)
- **Breakout**: $XX,XXX (Next target)

---
*Analysis by {model} | Not financial advice | DYOR*
""",
            "chart_data": {
                "labels": ["1h", "4h", "1d", "1w", "1M"],
                "prices": [100, 102, 105, 108, 112],
                "volumes": [1000, 1200, 1500, 1800, 2000],
            },
        },
        "metadata": {
            "model": model,
            "category": "trading",
        }
    }


# ==================== WEB UI COMPONENTS ====================

def render_sidebar() -> gr.Blocks:
    """Render the left sidebar with model router and settings."""
    
    with gr.Row(variant="panel", elem_classes="sidebar") as sidebar:
        # Model Status Panel
        with gr.Column(variant="panel"):
            gr.Markdown("# 🤖 Model Router Status")
            model_status = gr.JSON(
                value=hub.get_model_status(),
                label="System Status",
                elem_id="model-status",
            )
        
        # Engine Selector
        with gr.Column(variant="panel"):
            gr.Markdown("# 🎯 Engine Selector")
            category_dropdown = gr.Dropdown(
                choices=list(CATEGORY_ROUTERS.keys()),
                value="coding",
                label="Select Category",
                interactive=True,
            )
            
            model_dropdown = gr.Dropdown(
                choices=list(MODELS.keys()),
                value=list(CATEGORY_ROUTERS.values())[0],
                label="Select Model",
                interactive=True,
            )
        
        # Settings Panel
        with gr.Column(variant="panel"):
            gr.Markdown("# ⚙️ Settings")
            cloud_toggle = gr.Checkbox(
                value=True,
                label="Cloud Mode Only",
                info="All models run on cloud GPU - no local downloads",
            )
            connect_drive_btn = gr.Button("🔄 Refresh Drive", size="sm")
    
    return sidebar, category_dropdown, model_dropdown, cloud_toggle


def render_chat_canvas() -> Tuple[gr.Blocks, gr.Chatbot, gr.Textbox, gr.Button, gr.Dropdown, gr.Button]:
    """Render the central chat/canvas area."""
    
    with gr.Row(elem_classes="main-canvas") as canvas:
        # Chat area
        with gr.Column(scale=3, min_width=600) as chat_col:
            gr.Markdown("# 💬 Multi-Turn Chat")
            
            # Chat display
            chat_display = gr.Chatbot(
                label="Conversation",
                lines=10,
                interactive=False,
                placeholder="Messages will appear here...",
            )
            
            # Prompt input
            with gr.Row():
                prompt_input = gr.Textbox(
                    label="Enter Prompt",
                    placeholder="Describe what you want...",
                    scale=4,
                )
                send_btn = gr.Button("Send", scale=1)
        
        # Quick actions panel
        with gr.Column(scale=1, min_width=300) as actions_col:
            gr.Markdown("# ⚡ Quick Actions")
            
            quick_actions = gr.Dropdown(
                choices=[
                    "Code Generation",
                    "Image Creation",
                    "Video Synthesis",
                    "Voice/Audio",
                    "Research Report",
                    "Resume Builder",
                    "Trading Analysis",
                ],
                value="Code Generation",
                label="Quick Task",
            )
            
            execute_quick = gr.Button("Execute", size="sm")
    
    return canvas, chat_display, prompt_input, send_btn, quick_actions, execute_quick


def render_right_panel() -> Tuple[gr.Blocks, gr.Code, gr.Gallery, gr.Video, gr.Audio, gr.Code, gr.Plot]:
    """Render the right/lower panels for outputs."""
    
    with gr.Tabs(elem_classes="output-tabs") as tabs:
        
        # Code Editor Tab
        with gr.TabItem("💻 Code Editor", id="code-tab"):
            code_output = gr.Code(
                label="Generated Code",
                language="python",
                lines=20,
                interactive=False,
                show_line_numbers=True,
            )
        
        # Image Gallery Tab
        with gr.TabItem("🖼️ Image Gallery", id="image-tab"):
            image_gallery = gr.Gallery(
                label="Generated Images",
                columns=2,
                object_fit="contain",
                height=500,
            )
        
        # Video Player Tab
        with gr.TabItem("▶️ Video Player", id="video-tab"):
            video_player = gr.Video(label="Generated Video", height=400)
        
        # Audio Player Tab
        with gr.TabItem("🔊 Audio Player", id="audio-tab"):
            audio_player = gr.Audio(label="Generated Audio", type="filepath")
        
        # Research Report Tab
        with gr.TabItem("📊 Research Report", id="research-tab"):
            report_output = gr.Code(
                label="Research Findings",
                language="markdown",
                lines=30,
                interactive=False,
                show_line_numbers=True,
            )
        
        # Crypto Chart Tab
        with gr.TabItem("📈 Crypto Chart", id="crypto-tab"):
            crypto_chart = gr.Plot(label="Live Market Data")
    
    return tabs, code_output, image_gallery, video_player, audio_player, report_output, crypto_chart


# ==================== HANDLERS ====================

async def handle_route_prompt(
    category: str,
    prompt: str,
    model_name: str,
    cloud_mode: bool,
) -> Dict[str, Any]:
    """Handle routing a prompt to the unified hub."""
    
    if model_name not in MODELS:
        model_name = CATEGORY_ROUTERS.get(category, "qwen2.5-coder")
    
    model = MODELS[model_name]
    
    # Route through hub
    result = await hub.route_prompt(
        prompt=prompt,
        category=category,
        preferences={"cloud_mode": cloud_mode},
    )
    
    # Enhance with category-specific detailed output
    detailed = generate_category_output(category, prompt, model_name)
    result.update(detailed)
    
    return result


def on_category_change(category: str, model_dropdown: gr.Dropdown) -> str:
    """Handle category selection change."""
    if category in CATEGORY_ROUTERS:
        suggested = CATEGORY_ROUTERS[category]
        # Find in MODELS
        if suggested in MODELS:
            return suggested
    return model_dropdown.value


def on_send(
    prompt: str,
    category: str,
    model_name: str,
    cloud_mode: bool,
    chat_history: List,
) -> tuple:
    """Handle sending a prompt."""
    if not prompt.strip():
        return chat_history, "", category, model_name
    
    # Route the prompt
    result = asyncio.run(
        hub.route_prompt(prompt, category, {"cloud_mode": cloud_mode})
    )
    
    # Format result for display
    result_text = json.dumps(result, indent=2, default=str)
    
    # Update chat history
    new_history = chat_history + [
        (prompt, result_text),
    ]
    
    return new_history, "", category, model_name, ""


def save_session_data(session_name: str, data: dict) -> str:
    """Save session data to Google Drive."""
    path = save_to_drive(json.dumps(data, indent=2), f"sessions/{session_name}.json")
    return f"Saved to: {path}"


# ==================== LAUNCH FUNCTION ====================

def launch_dashboard() -> gr.Blocks:
    """Launch the complete Apeiron Web Dashboard."""
    
    with gr.Blocks(
        title="Apeiron Unified AI Hub",
        theme=gr.themes.Soft(),
        css="""
        .sidebar {background: #f8f9fa; border-right: 1px solid #e3e6e9;}
        .main-canvas {height: 800px;}
        .output-tabs .tab {font-weight: 600;}
        """,
    ) as app:
        
        # Header
        gr.Markdown("# 🏔️ Apeiron Unified AI Hub")
        gr.Markdown("*Central router for 47 open-source AI models*")
        
        # Sidebar
        sidebar = render_sidebar()
        
        # Main chat canvas
        canvas_results = render_chat_canvas()
        chat_display = canvas_results[1]
        prompt_input = canvas_results[2]
        send_btn = canvas_results[3]
        quick_actions = canvas_results[4]
        execute_quick = canvas_results[5]
        
        # Right panel
        panel_results = render_right_panel()
        tabs = panel_results[0]
        code_output = panel_results[1]
        image_gallery = panel_results[2]
        video_player = panel_results[3]
        audio_player = panel_results[4]
        report_output = panel_results[5]
        crypto_chart = panel_results[6]
        
        # ==================== EVENT HANDLERS ====================
        
        # Category change
        category_dropdown = sidebar.children[0].children[1]  # Simplified access
        # Actually let's set up properly
        
        with gr.Row():
            category_dropdown = gr.Dropdown(
                choices=list(CATEGORY_ROUTERS.keys()),
                value="coding",
                label="Category",
            )
            model_dropdown = gr.Dropdown(
                choices=list(MODELS.keys()),
                value="qwen2.5-coder",
                label="Model",
            )
        
        # Quick action execute
        execute_quick.click(
            fn=lambda sel: asyncio.run(
                hub.route_prompt(
                    f"Quick: {sel}",
                    "coding",
                    {"cloud_mode": True},
                )
            ),
            inputs=quick_actions,
            outputs=[code_output, image_gallery, video_player, audio_player, report_output],
        )
        
        # Send button
        send_btn.click(
            fn=on_send,
            inputs=[prompt_input, category_dropdown, model_dropdown, cloud_toggle],
            outputs=[chat_display, prompt_input, category_dropdown, model_dropdown, None],
        )
        
        # Text change in prompt
        prompt_input.submit(
            fn=on_send,
            inputs=[prompt_input, category_dropdown, model_dropdown, sidebar.children[0].children[0]],  # cloud toggle
            outputs=[chat_display, prompt_input, category_dropdown, model_dropdown, None],
        )
        
        # Model change
        model_dropdown.input(
            fn=on_category_change,
            inputs=[category_dropdown, model_dropdown],
            outputs=model_dropdown,
        )
    
    # Initialize chat state
    chat_display.value = json.dumps(hub.get_model_status(), indent=2)
    
    return app


# ==================== LAUNCH ====================

if __name__ == "__main__":
    # Launch the dashboard
    app = launch_dashboard()
    
    # Start server
    app.launch(
        host="0.0.0.0",
        port=7860,
        share=True,
        server_name="localhost",
    )